openapi: 3.0.0
info:
  title: "Queue"
  version: "1.0.0"
tags:
- name: "queues"
  description: "Queue operations"
- name: "rooms"
  description: "Rooms operations"
- name: "tickets"
  description: "Tickets operations"
- name: "users"
  description: "Users operations"

components:
  securitySchemes:
    user_auth:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/user/authorize
  schemas:
    Queue:
      type: "object"
      properties:
        id:
          type: integer
          maxLength: 10
        tenant:
          type: string
          maxLength: 36
        name:
          type: string
          maxLength: 32
        created_at:
          type: string
        updated_at:
          type: string

paths:
  /queue/get:
    get:
      tags:
      - "queues"
      summary: "Get a list of all queues"
      operationId: "getQueues"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  queues:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Queue"
      security:
      - user_auth: []

  /queue/create:
    post:
      tags:
      - "queues"
      summary: "Create a new queue"
      operationId: "createQueue"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  maxLength: 32
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  queues:
                    type: "object"
                    $ref: "#/components/schemas/Queue"
      security:
      - user_auth: []

  /queue/{queue_id}/remove:
    post:
      tags:
      - "queues"
      summary: "Remove a queue"
      operationId: "removeQueue"
      parameters:
        - in: path
          name: queue_id
          required: true
          schema:
            type: integer
            maxLength: 10
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  removed:
                    description: "Amount of queues removed"
                    type: "number"
      security:
      - user_auth: []
